### ISSUE TITLE
TokenUsedNotificationHandler not registered

### ISSUE THREAD

**Issue by g0dsCookie** [Scordo/TS3QueryLib.Net.Core#3]
Since there is no AddHandler for the "tokenused" event in the [NotificationHubs Initializer](https://github.com/Scordo/TS3QueryLib.Net.Core/blob/67898efd1bc3334306bf2613db20501151f416b5/TS3QueryLib.Net.Core/Server/Notification/NotificationHub.cs#L32) the TokenUsedNotificationHandler is never used.

**Comment by Scordo** [comment]
Thanks for the report. I'll fix that today - hopefully

**Comment by Scordo** [comment]
It's fixed in version [0.4.0-alpha](https://www.nuget.org/packages/TS3QueryLib.Net.Core/0.4.0-alpha).
