### ISSUE TITLE
Disconnect leaves open client connection

### ISSUE THREAD

**Issue by frostebite** [Scordo/TS3QueryLib.Net.Core#6]
Disconnect does not cause current clients or query to go down on server:

http://prntscr.com/hh37h8

then closing the application does cause the number to go down.

**Comment by frostebite** [comment]
This occurs with multiple conc

**Comment by MypowerHD** [comment]
Have the same Problem, How do you fix it?

**Comment by Scordo** [comment]
You should issues the following command before disconnecting:

`new QuitCommand().Execute(_client);`

The "Disconnect" is a close of the underlying raw socket (interrupt).
The QuitCommand issues a graceful logoff.
