### ISSUE TITLE
Events are invoked twice

### ISSUE THREAD

**Issue by Pandry** [Scordo/TS3QueryLib.Net.Core#8]
Hi,
I'm trying to figure this out from a couple of days:
The join event is invoked twice, and the disconnect one doesn't at all.
I've tried even the sample application provided in the repo, but the same thing happens.

**Comment by Pandry** [comment]
## Kinda "it works on my machine" error
I did try the application in another PC and the disconnect event fired...
I guess I'll try to debug by myself.
Anyway, all the events fired twice.

#### Edit
I figured out the disconnect event isn't triggered if the client is executed in the same host (or maybe IP, I'll check)
I did try to deploy yhe aplication on a server and the disconnect event did not fire for the client in my PC...

**Comment by Scordo** [comment]
I'll hopefully try to reproduce it at home today.

**Comment by Scordo** [comment]
Hi,

this is a bug in TS3-Server since the very early beginning,
I've created a report here, but it was never ever answered:
https://forum.teamspeak.com/threads/49640-Queryport-Some-notifications-are-sent-twice!

It's not a bug of this library. If you just use telnet to connect and register for the events on the server and on all channels the 2 events are fired twice.

**Comment by Pandry** [comment]
Oh, ok...
I did try to check the library and found nothing and I was kind of blaming the server, without being sure anyway...
Do you think the library should try to implement something like a "protection"?
(For example just storing the last string received and comparing with the successive message; I don't know if it's possible to receive 2 equal messages related to 2 different events)

**Comment by Scordo** [comment]
it would be possible to reveice 2 events which are equal but real. Like Messages.

**Comment by Scordo** [comment]
I've added a raw logging mechanism to the library. You can see it if you pull the latest version. When you use the test-client you can use "!log" to see the raw Messages sent and reveived. If you replay all the commands in a telenet client you'll see, that the events are also received twice.

**Comment by Pandry** [comment]
Yup,
I'm not familiar with the TS3 query language and I don't know if 2 messages can be the same even if they refer to different events

**Comment by Scordo** [comment]
The problem. Only exists for events. So I could implement an option to filter duplicate events if they are fired within a short timeframe.

**Comment by Pandry** [comment]
Do you want some help?

**Comment by Scordo** [comment]
Yeah you can try to fix the "bug" and do a Pull-Request.

**Comment by Scordo** [comment]
The necessary code block where to implement the check is:
https://github.com/Scordo/TS3QueryLib.Net.Core/blob/b4445ff70e3a60e821f836c4c9c267d702afb3d1/TS3QueryLib.Net.Core/QueryClient.cs#L231-L237

You should store the last received notification message and the datetime received. if the current mesage equals the last message and the Timespan is less than 200ms --> Ignore the message

**Comment by Pandry** [comment]
Ok. I've submitted the Pull Request (#9)...
Let me know if the comments and the variable names are in line with the project 😄

**Comment by Pandry** [comment]
Ok, I figured out it's not a Teamspeak problem:
If I ask for being notified about every channel (the 0, so every channel in this case) and the server too, a notification will be about a channel and one about the server...
So my question now is: if I subscribe to all the channel, am I subscribing to the server itself and/or vice-versa?

**Comment by Pandry** [comment]
I did try, and it looks like subscribing to all channels and the server at the same time doubles all the event I did try (and it's right I guess)...
So my question is if the PR should be accepted or not.

**Comment by Scordo** [comment]
The problem is, to get specific events like Server-wide Text-Messages, Joins and so on you have to subscribe to server events.
To get Channel-Based events like Messages in Channels you have to subscribe to each and every channel or subscribe to all channels by using "0".

So to get all events, for all channels and server you have to subscribe to both. And if you do, you'll get specific notifications twice.

**Comment by Pandry** [comment]
How about a flag that is used only if the lib listens for both Server and all channels events?
Or anyway give the possibility to enable a flag to check for double events

**Comment by Scordo** [comment]
I think the problem is solved with the "hacky" fix. I dont want to solve problems which the vendor of teamspeak should solve.

**Comment by Pandry** [comment]
And I agree with you (that's why it's `hacky` 😆)
